version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
